version: '3'
services:

 thumbor:
   image: liyyt/thumbor:latest
   build: .
   ports:
   - "80:80" # thumbor port
   environment:
     - DETECTORS=['thumbor.detectors.face_detector', 'thumbor.detectors.profile_detector', 'thumbor.detectors.feature_detector']
     - SECURITY_KEY=supersecretkey
